name       : prusa-slicer
version    : 2.6.0
release    : 13
source     :
    - https://github.com/prusa3d/PrusaSlicer/archive/refs/tags/version_2.6.0.tar.gz : a15f68e3b18a047c8c9a18a9d91629d2c777be1932087684cf6d2332d0888e77
license    : AGPL-3.0-or-later
component  : office
homepage   : https://www.prusa3d.com/prusaslicer/
summary    : G-code generator for 3D printers (RepRap, Makerbot, Ultimaker etc.) - 3D printing slicer
description: |
    PrusaSlicer takes 3D models (STL, OBJ, AMF) and converts them into G-code instructions for FFF printers or PNG layers for mSLA 3D printers. It's compatible with any modern printer based on the RepRap toolchain, including all those based on the Marlin, Prusa, Sprinter and Repetier firmware. It also works with Mach3, LinuxCNC and Machinekit controllers.
clang      : yes
networking : yes
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(blosc)
    - pkgconfig(eigen3)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(gtest)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(nlopt)
    - pkgconfig(tbb)
    - CGAL-devel
    - cereal
    - libboost-devel
    - openvdb-devel
    - wxwidgets-devel
    - git
environment: |
    export LDFLAGS="$LDFLAGS -z muldefs"
setup      : |
    sed -i 's/UNKNOWN/Solus/' version.inc
    #This is an uuuuugly hack, but until after the sync, this will do.
    pushd deps
    %cmake_ninja \
        -DDEP_WX_GTK3=ON
    %ninja_build
    popd
    %cmake_ninja \
        -DCMAKE_PREFIX_PATH=$workdir/deps/solusBuildDir/destdir/usr/local \
        -DSLIC3R_STATIC=1 \
        -DSLIC3R_FHS=ON \
        -DSLIC3R_PCH=OFF \
        -DSLIC3R_GTK=3

build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/PrusaSlicer/data
