name       : prusa-slicer
version    : 2.2.0
release    : 2
source     :
    - https://github.com/prusa3d/PrusaSlicer/archive/version_2.2.0.tar.gz : e6e0c83bf92e448ec058fd3063b84caca69f58b8b419e48eace6e8ce534937c0
license    : AGPL-3.0-or-later
component  : office
homepage   : https://www.prusa3d.com/prusaslicer/
summary    : G-code generator for 3D printers (RepRap, Makerbot, Ultimaker etc.) - 3D printing slicer
description: |
    PrusaSlicer takes 3D models (STL, OBJ, AMF) and converts them into G-code instructions for FFF printers or PNG layers for mSLA 3D printers. It's compatible with any modern printer based on the RepRap toolchain, including all those based on the Marlin, Prusa, Sprinter and Repetier firmware. It also works with Mach3, LinuxCNC and Machinekit controllers.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(blosc)
    - pkgconfig(eigen3)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(gtest)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(nlopt)
    - CGAL-devel
    - cereal
    - intel-tbb-devel
    - libboost-devel
    - openvdb-devel
    - wxwidgets-devel
setup      : |
    %cmake -DSLIC3R_WX_STABLE=1 -DSLIC3R_PCH=OFF -DSLIC3R_FHS=1 -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/prusa-slicer.desktop $installdir/usr/share/applications/prusa-slicer.desktop
    install -Dm00644 $installdir/usr/share/PrusaSlicer/udev/90-3dconnexion.rules $installdir/usr/lib/udev/rules.d/90-3dconnexion.rules
