name       : prusa-slicer
version    : 2.4.2
release    : 10
source     :
    - https://github.com/prusa3d/PrusaSlicer/archive/refs/tags/version_2.4.2.tar.gz : ac3a77212260e8d0baf9df027c29e0ae965bc77f371e59fd27b8fe103ebb1f23
license    : AGPL-3.0-or-later
component  : office
homepage   : https://www.prusa3d.com/prusaslicer/
summary    : G-code generator for 3D printers (RepRap, Makerbot, Ultimaker etc.) - 3D printing slicer
description: |
    PrusaSlicer takes 3D models (STL, OBJ, AMF) and converts them into G-code instructions for FFF printers or PNG layers for mSLA 3D printers. It's compatible with any modern printer based on the RepRap toolchain, including all those based on the Marlin, Prusa, Sprinter and Repetier firmware. It also works with Mach3, LinuxCNC and Machinekit controllers.
clang      : yes
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(blosc)
    - pkgconfig(eigen3)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(gtest)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(nlopt)
    - pkgconfig(tbb)
    - CGAL-devel
    - cereal
    - libboost-devel
    - openvdb-devel
    - wxwidgets-devel
setup      : |
    sed -i 's/UNKNOWN/Solus/' version.inc
    %cmake \
        -DSLIC3R_WX_STABLE=1 \
        -DSLIC3R_PCH=ON \
        -DSLIC3R_FHS=1 \
        -DOPENVDB_FIND_MODULE_PATH=/usr/lib/cmake/OpenVDB
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/PrusaSlicer/data
