name       : prusa-slicer
version    : 2.3.0
release    : 4
source     :
    - https://github.com/prusa3d/PrusaSlicer/archive/version_2.3.0.tar.gz : cd3bac5e29b5441fc4690f28cd7b1064e97dc00207bbdc88f7bd7832308d6ca5
license    : AGPL-3.0-or-later
component  : office
homepage   : https://www.prusa3d.com/prusaslicer/
summary    : G-code generator for 3D printers (RepRap, Makerbot, Ultimaker etc.) - 3D printing slicer
description: |
    PrusaSlicer takes 3D models (STL, OBJ, AMF) and converts them into G-code instructions for FFF printers or PNG layers for mSLA 3D printers. It's compatible with any modern printer based on the RepRap toolchain, including all those based on the Marlin, Prusa, Sprinter and Repetier firmware. It also works with Mach3, LinuxCNC and Machinekit controllers.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(blosc)
    - pkgconfig(eigen3)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(gtest)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(nlopt)
    - CGAL-devel
    - cereal
    - intel-tbb-devel
    - libboost-devel
    - openvdb-devel
    - wxwidgets-devel
setup      : |
    sed -i 's/UNKNOWN/Solus/' version.inc
    %cmake -DSLIC3R_WX_STABLE=1 -DSLIC3R_PCH=OFF -DSLIC3R_FHS=1 -DCMAKE_BUILD_TYPE=Release
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 $installdir/usr/share/PrusaSlicer/udev/90-3dconnexion.rules $installdir/usr/lib/udev/rules.d/90-3dconnexion.rules
    install -Dm00644 $installdir/usr/share/PrusaSlicer/applications/PrusaGcodeviewer.desktop $installdir/usr/share/applications/PrusaGcodeviewer.desktop
    install -Dm00644 $installdir/usr/share/PrusaSlicer/applications/PrusaSlicer.desktop $installdir/usr/share/applications/prusa-slicer.desktop

    install -Dm00644 $installdir/usr/share/PrusaSlicer/icons/PrusaSlicer_32px.png $installdir/usr/share/icons/hicolor/32x32/apps/PrusaSlicer.png
    install -Dm00644 $installdir/usr/share/PrusaSlicer/icons/PrusaSlicer_128px.png $installdir/usr/share/icons/hicolor/128x128/apps/PrusaSlicer.png
    install -Dm00644 $installdir/usr/share/PrusaSlicer/icons/PrusaSlicer_192px.png $installdir/usr/share/icons/hicolor/192x192/apps/PrusaSlicer.png

    install -Dm00644 $installdir/usr/share/PrusaSlicer/icons/PrusaSlicer-gcodeviewer_32px.png $installdir/usr/share/icons/hicolor/32x32/apps/PrusaSlicer-gcodeviewer.png
    install -Dm00644 $installdir/usr/share/PrusaSlicer/icons/PrusaSlicer-gcodeviewer_128px.png $installdir/usr/share/icons/hicolor/128x128/apps/PrusaSlicer-gcodeviewer.png
    install -Dm00644 $installdir/usr/share/PrusaSlicer/icons/PrusaSlicer-gcodeviewer_192px.png $installdir/usr/share/icons/hicolor/192x192/apps/PrusaSlicer-gcodeviewer.png

    rm -rf $installdir/usr/share/PrusaSlicer/data
